eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  PaymentService:
      endpoint:
        uri: http://Payment-Service/payment/doPayment
  OrderService:
      endpoint:
        uri: http://Order-Service/order/bookOrder    
